// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CdToNormalizeWorkingDir():Promise<void>;

export function GetCurrentEnvName():Promise<string>;

export function GetPATH():Promise<string>;

export function GetPlatform():Promise<string>;

export function GetRandomPid():Promise<number>;

export function LoadEnv():Promise<void>;

export function LogError(arg1:Error):Promise<void>;

export function LogErrorAndExit(arg1:Error):Promise<void>;

export function Pull():Promise<void>;

export function Push():Promise<void>;

export function RunRcloneSync(arg1:Array<string>):Promise<void>;

export function StopCommand(arg1:number):Promise<void>;
