// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CdToNormalizeWorkingDir() {
  return window['go']['main']['App']['CdToNormalizeWorkingDir']();
}

export function GetCurrentEnvName() {
  return window['go']['main']['App']['GetCurrentEnvName']();
}

export function GetPATH() {
  return window['go']['main']['App']['GetPATH']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetRandomPid() {
  return window['go']['main']['App']['GetRandomPid']();
}

export function LoadEnv() {
  return window['go']['main']['App']['LoadEnv']();
}

export function LogError(arg1) {
  return window['go']['main']['App']['LogError'](arg1);
}

export function LogErrorAndExit(arg1) {
  return window['go']['main']['App']['LogErrorAndExit'](arg1);
}

export function Pull() {
  return window['go']['main']['App']['Pull']();
}

export function Push() {
  return window['go']['main']['App']['Push']();
}

export function RunRcloneSync(arg1) {
  return window['go']['main']['App']['RunRcloneSync'](arg1);
}

export function StopCommand(arg1) {
  return window['go']['main']['App']['StopCommand'](arg1);
}
