// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {models} from '../models';
import {config} from '../models';

export function AddRemote(arg1:string,arg2:string,arg3:{[key: string]: string}):Promise<dto.AppError>;

export function DeleteRemote(arg1:string):Promise<void>;

export function GetConfigInfo():Promise<models.ConfigInfo>;

export function GetRemotes():Promise<Array<config.Remote>>;

export function StopAddingRemote():Promise<dto.AppError>;

export function StopCommand(arg1:number):Promise<void>;

export function Sync(arg1:string,arg2:models.Profile):Promise<number>;

export function UpdateProfiles(arg1:models.Profiles):Promise<dto.AppError>;
