// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfigInfo() {
  return window['go']['backend']['App']['GetConfigInfo']();
}

export function StopCommand(arg1) {
  return window['go']['backend']['App']['StopCommand'](arg1);
}

export function Sync(arg1) {
  return window['go']['backend']['App']['Sync'](arg1);
}

export function UpdateProfiles(arg1) {
  return window['go']['backend']['App']['UpdateProfiles'](arg1);
}
