// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Pull():Promise<number>;

export function Push():Promise<number>;

export function StopCommand(arg1:number):Promise<void>;

export function Sync(arg1:string):Promise<number>;
