// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetConfigInfo():Promise<models.ConfigInfo>;

export function StopCommand(arg1:number):Promise<void>;

export function Sync(arg1:string,arg2:models.Profile):Promise<number>;

export function UpdateProfiles(arg1:models.Profiles):Promise<void>;
